import { useState } from 'react';

interface HubAccessProps {
  checking: boolean;
  error: string | null;
  onLogin: (token: string) => Promise<void>;
}

export function HubAccess({ checking, error, onLogin }: HubAccessProps) {
  const [token, setToken] = useState('');

  return (
    <section className="launcher-panel">
      <div>
        <p className="eyebrow">Hub access</p>
        <h2>Protected control plane</h2>
        <p className="launcher-panel__copy">
          Enter the hub admin token generated by <code>omv hub init</code> or printed by <code>omv hub enroll browser</code>.
        </p>
      </div>
      <div className="launcher-panel__form">
        <label>
          <span>Admin token</span>
          <input
            type="password"
            value={token}
            onChange={(event) => setToken(event.target.value)}
            placeholder="Paste hub admin token"
          />
        </label>
        <button type="button" className="launcher-panel__save" onClick={() => void onLogin(token)} disabled={checking || !token.trim()}>
          {checking ? 'Signing in…' : 'Sign in'}
        </button>
      </div>
      <p className="launcher-panel__meta">{error ?? 'The dashboard requires an authenticated hub session.'}</p>
    </section>
  );
}
